etc/files:
  env: APP_CONFIG_FILE
  paths:
  - ./config/development.yaml
  - /etc/my-app/staging.yaml # This takes precedence over development.
  - /etc/my-app/production.yaml  # This takes precedence integration and development.


###
# With etc/entries we define the configuration map structure your
# application is going to be reading values from
etc/entries:

# Logging
  logging:
    verbose:
      etc/spec:
        default: true
        env: APP_LOG_VERBOSE
    handle:
      etc/spec:
        default: 'stdout'
        env: APP_LOG_HANDLE

# Webserver
  webserver:
    port:
      etc/spec:
        default: 3000
        type: number
        env: APP_WEB_PORT
        cli:
          input: option
          required: false
          long: web-port
          metavar: HTTP-PORT

# Database
  database:
    driver:
      etc/spec:
        default: sqlite
        type: string
        env: APP_DB_DRIVER
        cli:
          input: option
          required: false
          long: db-driver
          metavar: POSTGRES-OR-SQLITE

    username:
      etc/spec:
        default: test
        type: string
        env: APP_DB_USER
        cli:
          input: option
          required: false
          long: db-user
          metavar: DB-USERNAME

    password:
      etc/spec:
        default: qwerty
        type: string
        sensitive: true
        env: APP_DB_PASSWORD
        cli:
          input: option
          required: false
          long: db-password
          metavar: DB-PASSWORD

    port:
      etc/spec:
        default: '5432'
        type: string
        env: APP_DB_PORT

    database:
      etc/spec:
        default: opptest
        type: string
        env: APP_DB_NAME
        cli:
          input: option
          required: false
          long: db-name
          metavar: DB-NAME

    host:
      etc/spec:
        default: localhost
        type: string
        env: APP_DB_HOST
        cli:
          input: option
          required: false
          long: db-host
          metavar: DB-HOST